services:
  app_frontend_project_job:
    image: arturscibor/praca.strona.arturscibor.pl:latest
    env_file:
      - .env
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`praca.strona.arturscibor.pl`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=myresolver"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
