---
- name: Zaloguj do Docker Huba
  ansible.builtin.command:
    cmd: docker login -u {{ docker_hub_username }} --password-stdin
    stdin: "{{ docker_hub_password }}"
  no_log: true
  changed_when: false

- name: Deploy stacka frontendu
  ansible.builtin.command:
    cmd: >-
      docker stack deploy --with-registry-auth
      -c infra/dockerfiles/compose/prod.swarm.docker-compose.yaml
      {{ stack_name }}
    chdir: "{{ deploy_dir }}"
  environment:
    FRONTEND_IMAGE: "{{ frontend_image }}"
  changed_when: true
