name: Runner
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - developer
jobs:
  # dependencies-cache:
  #   uses: ./.github/workflows/dependencies.yml

  # cypress-run:
  #   needs: dependencies-cache
  #   uses: ./.github/workflows/test.yml

  # build:
  #   needs: cypress-run
  #   uses: ./.github/workflows/build.yml

  deploy:
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    run: |
      echo "Checking SSH_PRIVATE_KEY...."
      echo "LENGTH: $(echo -n "$SSH_PRIVATE_KEY" | wc -c)"
    # needs: build
    uses: ./.github/workflows/deploy.yml

  report:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong..."
          echo "${{toJSON(github)}}"
